### ISSUE TITLE
[Cannot run VM: VM is locked. Please try again in a few minutes.]

### ISSUE THREAD

**Issue by yalinglee** [imjoey/terraform-provider-ovirt#52]
When I use a template (which has a default disk) to create a VM with no additional disk attachment, I get `[Cannot run VM: VM is locked. Please try again in a few minutes.]` I believe this is because the VM disk is still in a locked state when the terraform provider tries to start the VM. Is it possible to add retry logic, or only start the VM when the disk is ready? 

Also, if I run `terraform apply` again (when the disk is ready), the terraform provider would actually detach the default disk attached to the VM, because terraform doesn't recognize the disk attachment as part of the state. Is there a way to reference the default disk in terraform so terraform apply is idempotent?

Here is my terraform code:
```
resource "ovirt_vm" "my_vm" {
  name      = "my_vm"
  cluster_id   = "${cluster_id}"
  template  = "my_tempate"
  cores     = 2
}
```

Here is the output: 
```
ovirt_vm.my_vm: Creating...
  cluster_id: "" => "3b1f3529-13bb-1420-0045-0000000002b1"
  cores:      "" => "2"
  name:       "" => "my_vm"
  sockets:    "" => "1"
  status:     "" => "<computed>"
  template:   "" => "my_tempate"
  threads:    "" => "1"

Error: Error applying plan:

1 error(s) occurred:

* ovirt_vm.my_vm: 1 error(s) occurred:

* ovirt_vm.my_vm: Fault reason is "Operation Failed". Fault detail is "[Cannot run VM: VM is locked. Please try again in a few minutes.]". HTTP response code is "409". HTTP response message is "409 Conflict".
```

If I run `terraform apply` again after the disk status is ready, I get 

```
ovirt_vm.my_vm: Refreshing state... (ID: 808d677c-9391-5088-9936-b1403a1d935a)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ ovirt_vm.my_vm
      attached_disk.#:                               "1" => "0"
      attached_disk.2279453186.active:               "true" => "false"
      attached_disk.2279453186.bootable:             "true" => "false"
      attached_disk.2279453186.disk_id:              "98257b05-a58d-4604-8315-6a8d974675d6" => ""
      attached_disk.2279453186.interface:            "virtio" => ""
      attached_disk.2279453186.logical_name:         "/dev/vda" => ""
      attached_disk.2279453186.pass_discard:         "false" => "false"
      attached_disk.2279453186.read_only:            "false" => "false"
      attached_disk.2279453186.use_scsi_reservation: "false" => "false"
      initialization.#:                              "1" => "0"
      initialization.0.host_name:                    "my_template" => ""


Plan: 0 to add, 1 to change, 0 to destroy.
```

After this, the disk attachment will be detached from the VM.

Please let me know if more details are needed. Thank!

**Comment by imjoey** [comment]
hi @yalinglee , thanks for your issues. We will fix them ASAP.

**Comment by bmanojlovic** [comment]
I have same issue with template, what could be maybe done is something like, 
-  create  vm with template
- if template != blank, wait till VM is created
-  when ready read disk attachments, vnic, and other info
- apply required/requested changes vs real state  of VM, so if disk exist from template do not remove it (extend  to size, do not change if different type and so on)
- apply required/requested changes vs real state  of VM, so if vnic exist from template do not remove it only change if possible

to be honest still no clue how to do that, it is more of brainstorming :)

**Comment by imjoey** [comment]
Exactly, yes. 

The `attached_disk` field is to designed to **explicitly** and **totally** indicate the disks that have been attached to a VM. While the disks that derived from a `template` ( or a `snapshot`) are not able to be specified, because oVirt does not record about the relationship between a disk and its *parent* `template`.

I've tried to look for an property like `metadata` or `tag`, which could store the *parent* `template` ID in `disk` entity, but unfortunately not exist.

So until now, this issue is still in the air.

**Comment by nvtkaszpir** [comment]
Notice, that you can create a vm template in two ways:
- with thinly provisioned disk (template is parent and new vm from template is a difference file from parent)
- with full disk clone (ovirt makes a new disk by copying a parent and then the disk is an indepndent one) - this may be a reason why you do not see dependency

**Comment by imjoey** [comment]
Thanks @nvtkaszpir , that does make sense. 

After looked through the implementations of [*_block_device in resource_aws_instance](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_instance.go) and [block_device in resource_openstack_compute_instance_v2](https://github.com/terraform-providers/terraform-provider-openstack/blob/master/openstack/resource_openstack_compute_instance_v2.go), I realized that Terraform is no need to manage everything in backend system. 

So my current solution is that rather than the disks/nics created based on a template, Terraform would only assume the manage of the disks/nics explicitly indicated by users/configs.

If you have other methods, please let me know. Thanks.

**Comment by nvtkaszpir** [comment]
@imjoey is right, this is true especially with templates, which assume certain core system components to be inherited from template and terraform/other provisioning tools do not have to know.

It may be worth to look into ovirt modules for Ansible, which also allow to talk with oVirt API and work tremendously well (no wonder, since RedHat took Ansible and oVirt under their  supervision).
source: https://github.com/ansible/ansible/tree/devel/lib/ansible/modules/cloud/ovirt
docs: https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules.html#ovirt

**Comment by imjoey** [comment]
@nvtkaszpir It's awesome and the very thing that I want!  Great thanks for you.

The ovirt modules for Ansible notes the `disks` parameter in `ovirt_vms`with:

```
NOTE - This parameter is used only when state is running or present and is able to only attach disks. To manage disks of the VM in more depth please use ovirt_disks module instead.
```

While for the `nics` parameter in `ovirt_vms` is:

```
NOTE - This parameter is used only when state is running or present and is able to only create NICs. To manage NICs of the VM in more depth please use ovirt_nics module instead.
```

As the notes mentioned above, the preceding solution may probably worked. 😄

**Comment by imjoey** [comment]
hi @yalinglee @bmanojlovic @nvtkaszpir , #56 which brings lots of changes about VM disk and vnic has been merged. This pull request aims to fix the issues as @yalinglee and @bmanojlovic mentioned.

It is to make the disks/vnics derived from template in a VM are excluded in the control of Terraform and Terraform will only take care of the ones explicitly indicated by `ovirt_disk_attachment` and `ovirt_vnic`. For more details and usage, please see #56 and the latest `main.tf` configuration file.

**Comment by yalinglee** [comment]
@imjoey This works for me now. Thank you!

**Comment by imjoey** [comment]
@yalinglee Thanks for your confirmation. Close it now. Please feel free to reopen this if there is any problem. 😄
